Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m2.208s
user	0m1.266s
sys	0m0.197s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.688s
user	0m1.223s
sys	0m0.185s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.769s
user	0m1.257s
sys	0m0.174s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.763s
user	0m1.257s
sys	0m0.173s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.735s
user	0m1.249s
sys	0m0.172s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.736s
user	0m1.284s
sys	0m0.153s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.734s
user	0m1.265s
sys	0m0.166s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.750s
user	0m1.263s
sys	0m0.161s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.734s
user	0m1.275s
sys	0m0.154s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.694s
user	0m1.255s
sys	0m0.146s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.707s
user	0m1.272s
sys	0m0.162s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.714s
user	0m1.260s
sys	0m0.167s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.746s
user	0m1.276s
sys	0m0.156s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.756s
user	0m1.291s
sys	0m0.150s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.778s
user	0m1.248s
sys	0m0.166s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.873s
user	0m1.246s
sys	0m0.159s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.773s
user	0m1.228s
sys	0m0.190s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.741s
user	0m1.284s
sys	0m0.148s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.741s
user	0m1.290s
sys	0m0.162s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 159, in <module>
    model = generate_model(arch_str)
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 46, in generate_model
    modules.append(activation_dict[activation]())
KeyError: 'EluTanh'

real	0m1.785s
user	0m1.292s
sys	0m0.169s
