
real	0m25.088s
user	0m22.206s
sys	0m1.172s

real	1m43.055s
user	1m31.116s
sys	0m9.254s

real	0m37.000s
user	0m32.719s
sys	0m2.437s

real	1m28.896s
user	1m21.362s
sys	0m5.358s

real	0m38.197s
user	0m32.638s
sys	0m3.555s

real	1m48.292s
user	1m35.733s
sys	0m9.433s

real	0m34.714s
user	0m31.994s
sys	0m1.375s

real	1m45.368s
user	1m33.183s
sys	0m9.273s

real	0m31.979s
user	0m28.413s
sys	0m2.062s

real	1m27.951s
user	1m15.903s
sys	0m9.326s

real	0m30.008s
user	0m27.405s
sys	0m1.299s

real	1m18.157s
user	1m14.271s
sys	0m1.991s

real	0m30.018s
user	0m26.600s
sys	0m1.903s
Traceback (most recent call last):
  File "/home/thiago.esterci/2D_imune_edema_pinn/edo_pinn_model.py", line 176, in <module>
    Cp = pk.load(f)
EOFError: Ran out of input

real	0m1.944s
user	0m1.301s
sys	0m0.185s

real	0m34.522s
user	0m28.863s
sys	0m3.826s

real	1m35.470s
user	1m24.109s
sys	0m8.327s

real	0m34.882s
user	0m28.691s
sys	0m4.575s

real	1m27.789s
user	1m16.256s
sys	0m8.825s

real	0m27.931s
user	0m24.585s
sys	0m1.812s

real	1m30.445s
user	1m18.750s
sys	0m8.955s
